### PR TITLE
completeMultipartUpload fix

### PR DESCRIPTION
**Pull request by Nlammertyn**
The issue was that files larger than 5MB weren't being uploaded correctly (they were finished but they were missing a bit of data at the end) and resulted in an error, that forced the server to restart.

Line 56 is not fired for the last file as it's size is never greater than the maxSize

This means there is no callback on line 115 and the receivedSize isn't being incremented before landing on line 140. Thus the if statement returns true and completeMultipartUpload is being called.

Only then the flushChunk on line 70 is called, but since completeMultipartUpload has already been called, it is too late. The file on S3 has been finished without the last chunk and completeMultipartUpload has been called a 2nd time, resulting in a bug as the files have already been deleted.

The fix consists of adding a boolean to indicate if the last chunk is calling the flushChunk(). If not the completeMultipartUpload won't be triggered.

### CODE REVIEW

**Comment by raix** [comment]
@Nlammertyn Impressive detective work! I'll merge and do some qa, its much appreciated! Thank you :)

**Comment by Nlammertyn** [comment]
You're very welcome ;)

**Comment by tom2strobl** [comment]
Is this already pushed to meteor? Because somehow it didn't end up in my local build I think.

**Comment by Nlammertyn** [comment]
I don't think so, you could download the package add it to your packages folder and add it manually for now.

**Comment by aldeed** [comment]
Sorry, I will publish now

**Comment by aldeed** [comment]
https://github.com/CollectionFS/Meteor-cfs-s3/releases/tag/v0.1.2

**Comment by tom2strobl** [comment]
Thanks so much for the incredibly fast push aldeed and of course Nlammertyn for the fix!

**Pull request merged**
